### ISSUE TITLE
energy_uj is no longer readable

### ISSUE THREAD

**Issue by Calchan** [FeralInteractive/gamemode#337]
**Describe the bug**
As per:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/h=v5.4.77&id=19f6d91bdad42200aac557a683c17b1f65ee6c94
read access to `/sys/class/powercap/intel-rapl*/*/energy_uj` for non-privileged users is no longer allowed.

This appeared in kernel 5.4.77.

Since `gamemoded` should be started as a user service, it no longer has access to these system interfaces which means the iGPU governor feature is now broken.

**To Reproduce**
Steps used to reproduce the behavior:
1. Launch gamemod via `systemctl --user start gamemoded.service`
2. Run `gamemode-simulate-game` or `gamemoded -t`
3. Monitor the output of `journalctl -f -n 0`
4. See error: `Failed to open file for read /sys/class/powercap/intel-rapl/intel-rapl:0/intel-rapl:0:0/energy_uj`

**Expected behavior**
Not seeing the error above and being able to use the iGPU governor feature.

**System Info (please complete the following information):**
 - OS and version: debian sid/experimental with kernel 5.13.9
 - GameMode Version: 1.6.1

**Additional context**
I use the script below started as a system (i.e., not user) systemd service, then add users who need GameMode to the `games` group. 

```
#! /bin/bash

for NAME_PATH in $(find /sys/class/powercap/intel-rapl/intel-rapl\:0/intel-rapl\:0\:* -name name || true); do
    NAME=$(cat "${NAME_PATH}")
    if [[ "${NAME}" == "core" ]] || [[ "${NAME}" == "uncore" ]]; then
         DIR_NAME=$(dirname "${NAME_PATH}")
         chown root:games "${DIR_NAME}/energy_uj"
         chmod g+r "${DIR_NAME}/energy_uj"
    fi
done
```

It's a bit crude but it works. It seems this needs to be fixed with GameMode providing a script and systemd service like I do (or any better solution, or at least documentation of the issue and example of possible resolution), or the iGPU governor feature should be removed.

**Comment by linjuhh** [comment]
Still having this issue, after trying this workaround I stopped getting permission denied errors and now get invalid argument errors(using no config file or the example config file).
Kernel 5.14.2-1-MANJARO.

**Comment by leemm** [comment]
> I use the script below started as a system (i.e., not user) systemd service, then add users who need GameMode to the `games` group.

Thanks for this, it's a nice albeit slightly hacky trick but it works on my system too (Ubuntu 20.04).

**Comment by rscm** [comment]
still happens

(user _is_ in gamemode group)

```
System Information: Lenovo Legion 5 15ARH05H
CPU: AMD 4800H
iGPU: AMD Renoir
dGPU: Nvidia RTX2060
OS: Fedora 41 Silverblue
```

```
❯ rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/41/x86_64/silverblue
                  Version: 41.20241212.0 (2024-12-12T00:41:34Z)
               BaseCommit: 6e2ac99d3100ce7c20b79b1729ba193caf3d71e6a99cbcf1925e117b573ddbf7
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1
      RemovedBasePackages: firefox firefox-langpacks 133.0-2.fc41 wpa_supplicant 1:2.11-3.fc41
          LayeredPackages: akmod-nvidia android-tools distrobox gnome-tweaks gparted iwd kitty printer-driver-brlaser rpmfusion-free-release rpmfusion-nonfree-release starship steam-devices tailscale xboxdrv
                           xorg-x11-drv-nvidia xorg-x11-drv-nvidia-cuda
            LocalPackages: akmod-openrazer-100.0.0.git.588.1d12f502-1.fc41.x86_64 kmod-openrazer-100.0.0.git.588.1d12f502-1.fc41.x86_64 openrazer-kmod-common-100.0.0.git.588.1d12f502-1.fc41.x86_64
```
```
❯ uname -r
6.11.11-300.fc41.x86_64
```
Gamemode
`gamemode-1.8.2-1.fc41.x86_64`


Ran after loading a game in Steam (flatpak)
```
❯ systemctl status --user gamemoded.service
● gamemoded.service - gamemoded
     Loaded: loaded (/usr/lib/systemd/user/gamemoded.service; disabled; preset: disabled)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Sun 2024-12-15 13:56:53 -03; 47s ago
 Invocation: e77ab6c71440413d9c8da7ff580f9ca1
   Main PID: 8781 (gamemoded)
     Status: "GameMode is now active."
      Tasks: 2 (limit: 18105)
     Memory: 1.2M (peak: 4.5M)
        CPU: 42ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/gamemoded.service
             └─8781 /usr/bin/gamemoded

dic 15 13:56:53 LEGION systemd[1511]: Starting gamemoded.service - gamemoded...
dic 15 13:56:53 LEGION systemd[1511]: Started gamemoded.service - gamemoded.
dic 15 13:56:53 LEGION gamemoded[8781]: ERROR: Failed to open file for read /sys/class/powercap/intel-rapl/intel-rapl:0/intel-rapl:0:0/energy_uj
dic 15 13:56:53 LEGION gamemoded[8781]: ERROR: Skipping ioprio on client [8777,8777]: ioprio was (0) but we expected (4)
dic 15 13:56:53 LEGION gamemoded[8781]: ERROR: Addition requested for already known client 8777 [/usr/bin/env].
dic 15 13:56:53 LEGION gamemoded[8781]:     -- This may happen due to using exec or shell wrappers. You may want to
dic 15 13:56:53 LEGION gamemoded[8781]:     -- blacklist this client so GameMode can see its final name here.
dic 15 13:56:53 LEGION gamemoded[8781]: ERROR: Addition requested for already known client 8777 [/usr/bin/env].
dic 15 13:56:53 LEGION gamemoded[8781]: ERROR: Skipping ioprio on client [8831,8831]: ioprio was (0) but we expected (4)
dic 15 13:56:53 LEGION gamemoded[8781]: ERROR: Skipping ioprio on client [8832,8832]: ioprio was (0) but we expected (4)
```
